config/routes.rb
Rails.application.routes.draw do
    root 'welcome#home'
    get 'signup' => 'users#new'

    get 'login' => 'sessions#new'
    post 'login' => 'sessions#create'
    delete 'logout' => 'sessions#destroy'

    resources :users
    resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
    belongs_to :user

    validates :title,
        presence: true,
        length: {minimum: 3, maximum: 50}

    validates :description,
        presence: true,
        length: {minimum: 10, maximum: 300}

    validates :user_id,
        presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
    has_many :articles

    before_save { self.email = email.downcase }

    validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }

    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

    validates :email, presence: true, uniqueness: { case_sensitive: false }, length: { maximum: 100 }, format: {with: VALID_EMAIL_REGEX}

    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def index
      render component: 'ArticleList', props: { articles: Article.all }
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "Article was created"
            redirect_to articles_path
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if @article.update(article_params)
            flash[:notice] = "Article was updated"
            redirect_to articles_path
        else
            render :new
        end
    end

    def destroy
      @article.destroy
      respond_to do |format|
        format.js
      end
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new

    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user && user.authenticate(params[:session][:password])
            session[:user_id]
            flash[:success] = "You successfully logged in"
            redirect_to user_path(user)
        else
            flash.now[:danger] = "Something wrong with your login information"
            render 'new' 
        end
    end

    def destroy
        session[:user_id] = nil
        flash[:success] = "You have logged out"
        redirect_to root_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def index
        @users = User.all
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            redirect_to articles_path
        else
            render :new
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def show
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            flash[:success] = "Your account was updated successfully"
            redirect_to articles_path
        else
            render 'edit'
        end
    end

    private
    def user_params
        params.require(:user).permit(:email, :username, :password)
    end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
    def home
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username)
  end

  def flash_messages
    capture do
      flash.each do |type, message|
        concat content_tag(:div, message, class: "alert alert-#{type}", role: 'alert')
      end
    end
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<h5>Edit an article</h5>
<div class="row">
    <div class="col s6 offset-s3">
        <%= render 'partials/form' %>
    </div>
</div>

app/views/articles/new.html.erb
<div class="row">
    <div class="col s6 offset-s3">
        <h4>Create a new article</h4>
    </div>
</div>
<%= render 'partials/form' %>

app/views/articles/show.html.erb
<div class="row">
    <div class="col s4 offset-s4">
        <h3><%= @article.title %></h3>
        <p>By: <%= link_to  @article.user.username, user_path(@article.user) %></p>
    </div>
</div>
<div class="row">
    <div class="col s6 offset-s3">
        <p><%= @article.description %></p>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>ShMedium</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/css/materialize.min.css">
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    </head>
    <body>
        <nav class="green accent-3">
            <div class="nav-wrapper">
                <a href="#" class="brand-logo">ShMedium</a>
                <ul id="nav-mobile" class="right hide-on-med-and-down">
                    <li><a href="/">Home</a></li>
                    <li><%= link_to "Articles", articles_path %></li>
                    <li><%= link_to "Create", new_article_path %></li>
                    <li><a href="/signup">Sign Up</a></li>
                    <li><%= link_to "Logout", logout_path, method: :delete %></li>
                </ul>
            </div>
        </nav>
        <%= flash_messages %>
        <%= yield %>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.6/js/materialize.min.js" data-turbolinks-eval=false></script>
    </body>
</html>

app/views/partials/_form.html.erb
<% if @article.errors.any?  %>
    <h4>The Following Errors prevented the article form being created</h4>
    <ul>
        <% @article.errors.full_messages.each do |msg| %>
            <li><%= msg  %></li>
        <% end %>
    </ul>
<% end %>


<div class="row">
    <div class="col s6 offset-s3">
        <%= form_for @article do |f| %>
            <div class="input-field">
                <%= f.label :title, class: "" %>
                <%= f.text_field :title, class: "" %>
            </div>

            <div class="input-field">
                <%= f.label :description, class: "" %>
                <%= f.text_area :description, class: "materialize-textarea" %>
            </div>
            <%= f.submit class: "waves-effect waves-light btn"%>
        <% end %>
    </div>
</div>

app/views/users/_form.html.erb
<div class="row">
    <div class="col s6 offset-s3">
        <%= form_for @user do |f| %>
            <div class="input-field">
                <%= f.label :username, class: "" %>
                <%= f.text_field :username, class: "" %>
            </div>

            <div class="input-field">
                <%= f.label :email, class: "" %>
                <%= f.email_field :email, class: "" %>
            </div>

            <div class="input-field">
                <%= f.label :password, class: "" %>
                <%= f.password_field :password, class: "materialize-textarea" %>
            </div>
            <%= f.submit (@user.new_record? ? 'Sign Up' : 'Update account'), class: "waves-effect waves-light btn"%>
        <% end %>
    </div>
</div>

app/views/users/edit.html.erb
<h3> Edit your account </h3>

<%= render 'form' %>

app/views/users/index.html.erb
<div class="row">
    <div class="col m4 offset-m4 l4 offset-l4 s6 offset-s3">
        <h4>User Directory</h4>
    </div>
</div>
<div class="row">
    <% @users.each do |user| %>
        <div class="col s12 m3 l3">
            <div class="card">
                <div class="card-content">
                    <span class="card-title"><%= user.username %></span>
                    <div>
                        <%= gravatar_for(user) %>
                    </div>
                </div>
                <div class="card-action">
                    <a><%= link_to 'Profile', user_path(user) %></a>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/users/new.html.erb
<div class="row">
    <div class="col s6 offset-s3">
        <h2>Sign Up for ShMedium</h2>
    </div>
</div>
<% if @user.errors.any?  %>
    <h4>The Following Errors prevented the article form being created</h4>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

<%= render 'form' %>

app/views/users/show.html.erb
<div class="row">
    <div class="col s6 offset-s3">
        <h4>Welcome to <%= @user.username %>'s page</h4>
        <%= gravatar_for @user %>
        <h5><%= @user.username %>'s articles</h5>
        <%= render 'partials/articles', obj: @user.articles %>
    </div>
</div>

app/views/welcome/home.html.erb
<h1 class="header center">Welcome To ShMedium</h1>
<h5 class="center">The not so great Medium clone</h5>
<br>
<br>
<br>
<br>
<div class="container">
    <div class="section">
        <div class="row">
            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center"><i class="large material-icons">language</i></h2>
                    <h5 class="center">Read Stories From Around The Globe</h5>
                    <p class="light">Read about all the amazing adventures that people have through the great stories posted on ShMedium</p>
                </div>
            </div>

            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center"><i class="large material-icons">group</i></h2>
                    <h5 class="center">User Experience Focused</h5>
                    <p class="light">With a light weight desgin and plenty of white space, ShMedium is every bloggers dream</p>
                </div>
            </div>

            <div class="col s12 m4">
                <div class="icon-block">
                    <h2 class="center"><i class="large material-icons">settings</i></h2>
                    <h5 class="center">Easy to work with</h5>
                    <p class="light">Just start typing and post when you are finish. It's that easy! User login system to come</p>
                </div>
            </div>
        </div>
    </div>
</div>